---
title: "ELToD Results"
author: "Amar Sarvepalli"
date: "July 27, 2017"
output:
  flexdashboard::flex_dashboard:
    keep_md: yes
    theme: united
---


```{r User_Settings, echo=FALSE, message=FALSE, warning=FALSE}
#======================================================================
# Read data files
#======================================================================
  # Path settings
  dir_path     <- "C:/projects/R-projects/ELToD_Visualization"
  dir.Data     <- "Data"
  dir.Scenario <- "Veterans"
  dir.ELToD    <- "ELToD Results"
  dir.Analysis <- "Analysis"
  dir.Shape    <- "Project_Shape"
  
  # Scenario settings
  policy    <- c("oldPolicy", "newPolicy")
  scenarios <- c("Y2020Rev", "Y2040Rev")
  Years     <- c(2020, 2040)
  
  # filenames and pull links
  filenames <- paste0("VOL",c(1:24),".csv")
  pull_link <- "Pull_Link_Dir.csv"
  
  # output excel files, segment starting rows
  excel_template <- "Template.xlsx"
  segments <- c(1,2)
  seg_data_start_rows <- c(6, 51)
  sheet_name = "Output"
  old_outfiles <- c("Output_2020A1.xlsx", "Output_2040A1.xlsx")
  new_outfiles <- c("Output_2020A2.xlsx", "Output_2040A2.xlsx")
  
  # Excel Summary file
  # A choice to read data from excel spreadsheets instead of standard ELToD outputs
  read_from_excel <- TRUE
  
  # when read_from_excel is false, should it write to excel summaries
  export_summaries_to_excel <- FALSE
  
  # write interim master database file (df)
  writeMasterDb <- TRUE
  
  # print selected plots
  plotsPDF <- TRUE
  pdf_output <- "Veterans_Expressway.pdf"
    
  # Display project on map (Dashboard 'Summary' tab)
  display_Project <- TRUE
  shape_file      <- "Veterans_v2.shp"
  map_center_lat  <-  28.0396  
  map_center_lng  <- -82.5463 
  map_zoom        <-  11
  map_title       <- "Veterans Expressway"
```



```{r child = 'R/Build_ELToD_Dashboard.Rmd'}

```

