---
title: "ELToD Results"
author: "Amar Sarvepalli"
date: "July 27, 2017"
output:
  flexdashboard::flex_dashboard:
    keep_md: yes
    theme: united
  navbar:
  - align: left
    title: About
---


```{r setup, include=FALSE}

#======================================================================
# Check and install libraries 
#======================================================================
  required_packages <- c("knitr", "flexdashboard",
                         "dplyr", "tidyr", 
                         "DT", "data.table", "XLConnect", "foreign",
                         "plotly", "rgdal", "leaflet")
  
  check_packages <- required_packages %in% rownames(installed.packages())
  missing_packages <- required_packages[check_packages == FALSE]
  
  if (length(missing_packages) > 0) {
    install.packages(missing_packages)
  }
  
  sapply(required_packages, library, character.only = TRUE)
  
  
  # Set chunk options
  opts_knit$set(root.dir=normalizePath('../'))
  opts_chunk$set(
  	echo = FALSE,
  	message = FALSE,
  	warning = FALSE,
  	fig.path = "figures/",
    dev = 'png',
    fig.keep = 'all',
  	dev.args=list(type="cairo")
  )
  
  
  options(DT.options = list(pageLength = 5, language = list(search = 'Filter:')),
          initComplete = JS(
          "function(settings, json) {",
          "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
           "}"),
          searchHighlight = TRUE, filter = 'none')

  config(plot_ly(), displaylogo = FALSE, collaborate = FALSE)
```



```{r User_Settings, echo=FALSE, message=FALSE, warning=FALSE}
#======================================================================
# Read data files
#======================================================================
  # Path settings
  dir_path     <- "C:/projects/R-projects/ELToD_Visualization"
  dir.Data     <- "Data"
  dir.Scenario <- "Veterans"
  dir.ELToD    <- "ELToD Results"
  dir.Analysis <- "Analysis"
  dir.Shape    <- "Project_Shape"
  
  # Scenario settings
  policy    <- c("oldPolicy", "newPolicy")
  scenarios <- c("Y2020Rev", "Y2040Rev")
  Years     <- c(2020, 2040)
  
  # filenames and pull links
  filenames <- paste0("VOL",c(1:24),".csv")
  pull_link <- "Pull_Link_Dir.csv"
  
  # output excel files, segment starting rows
  excel_template <- "Template.xlsx"
  segments <- c(1,2,3)
  seg_data_start_rows <- c(6, 51, 96)
  sheet_name = "Output"
  old_outfiles <- c("Output_2020A1.xlsx", "Output_2040A1.xlsx")
  new_outfiles <- c("Output_2020A2.xlsx", "Output_2040A2.xlsx")
  
  # Excel Summary file
  # A choice to read data from excel spreadsheets instead of standard ELToD outputs
  read_from_excel <- TRUE
  
  # when read_from_excel is false, should it write to excel summaries
  export_summaries_to_excel <- FALSE
  
  # Display project on map (Dashboard 'Summary' tab)
  display_Project <- TRUE
  shape_file      <- "Veterans_v2.shp"
  map_center_lat  <-  28.0396  #  26.13874  
  map_center_lng  <- -82.5463  # -80.3155  
  map_zoom        <-  11
  map_title       <- "VETERANS Expressway"
```


```{r generate_input_file_fullpaths}

  # Declare all sub-directory paths
  proj_path <- paste(dir_path, dir.Data, dir.Scenario, sep = "/") 
  file_path <- paste(proj_path, dir.ELToD, sep = "/")
  analysis_path <- paste(proj_path, dir.Analysis, sep = "/")
  shape_path <- paste(proj_path, dir.Shape, sep = "/")
  
  # Input file full-paths
  pull_link_full_path <- paste(file_path, pull_link, sep="/") 
  excel_template_full_path <- paste(file_path, excel_template, sep="/") 
  shape_file_full_path <- paste(shape_path, shape_file, sep="/") 

```


```{r read_model_outputs}

  # Read ELToD raw files
  if (!read_from_excel) {
    source(paste0(dir_path,'/R/Read_ELToD_Outputs.R'))
    
    # Export ELToD Sumamries to Spreadsheets
    if(export_summaries_to_excel){
      source(paste0(dir_path,'/R/Export_ELToD_Output.R'))
      
    }
  } else {
    
    # Read ELToD Summaries from Anslysis Spreadsheet
    source(paste0(dir_path,'/R/Read_ELToD_Summaries.R'))
  }
   

```


```{r plot volume function}
   # load function to animate
   source(paste0(dir_path,'/R/Function_To_Plot_Volumes.R'))
```


```{r child = '/R/Volumes_by_Segment.Rmd'}

```



```{r child = '/R/Summary.Rmd'}

```



```{r child = 'R/LOS_by_Segment.Rmd'}

```

