---
title: "LOS_By_Segments"
author: "Amar Sarvepalli"
date: "September 7, 2017"
output: 
    flexdashboard::flex_dashboard:
---

Year 2040: Anderson Test {data-navmenu="LOS"} 
=====================================

Column {data-width=350}
-------------------------------------
### Level of Service (LOS) 

* LOS A: V/C below 0.3
* LOS B: V/C between 0.3 and 0.5
* LOS C: V/C above 0.5

### EL Volumes
```{r}
 los_EL %>%
 filter(Year == 2040, Seg == 2) %>% plot_los()

```

### EL Shares
```{r}
 los_EL_shares %>%
 filter(Year == 2040, Seg == 2) %>% plot_los()

```

### Trips Paying
```{r}
 los_paying %>%
 filter(Year == 2040, Seg == 2) %>% plot_los()

```


Column 
-------------------------------------

### 2040: Old Policy Segment 2: Anderson

```{r}
old_policy_2040_seg2 <- df_old_policy_2040_seg2 %>%
              gather( -Hour, key = direction, value = VC) %>%
              select(Hour, direction, VC ) %>% 
              plot_voc()

old_policy_2040_seg2

```


### 2040: New Policy Segment 2: Anderson

```{r}

new_policy_2040_seg2 <- df_new_policy_2040_seg2  %>%            
              gather( -Hour, key = direction, value = VC) %>%
              select(Hour, direction, VC ) %>% 
              plot_voc()

new_policy_2040_seg2

```

